### ISSUE TITLE
replace 'request' with 'http.min'

### ISSUE THREAD

**Issue by bvdbos** [jordenc/com.lg.smarttv#1]
Somehow there seems to be an error in the combination of Homey and request.js... Replacing request with http.min seems to give very positive results:
https://athomcommunity.slack.com/archives/developers/p1465328720000123

**Comment by jordenc** [comment]
I don't use the request library. The request.js file can be deleted, it was only there because it's the original file that this app is based on, so I could copy code.

The 'http' library is used for almost everything. I think the 'Connection refused' messages are just messages from TV's that use a different system and they need to be addressed differently. However, I am no expert on LG televisions, so I am not sure about that.

**Comment by bvdbos** [comment]
closing....

**Comment by jordenc** [comment]
Geachte heer, mevrouw,

Tot woensdag 8 februari ben ik afwezig wegens vakantie.

Voor dringende zaken kunt u contact opnemen met mijn collega Martin Kruijff via info@totallyhosted.nl

Met vriendelijke groet,
Jorden Chamid

**Comment by bvdbos** [comment]
lol
